site_name: ThinkNotes
theme:
  name: material
  palette:
    primary: green
    accent: yellow
    scheme: slate
    toggle:
      icon: material/brightness-4
  font: 
    text: IBM Plex Serif
    code: Roboto Mono, 10
markdown_extensions:
  - pymdownx.highlight:
      pygments_style: 'bw'
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
