site_name: ThinkCode
theme:
  name: material
  palette:
    primary: deep purple
    accent: light green
    scheme: slate
    toggle:
      icon: material/brightness-4
  font: 
    text: IBM Plex Serif
    code: IBM Plex Mono
markdown_extensions:
  - pymdownx.highlight:
      pygments_style: 'bw'
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
